register/urls.py
from django.urls import path
from . import views
from .views import (
    RegisterCreateView,
    MassListView
)

urlpatterns = [
    path('', MassListView.as_view(), name='register-home'),
    path('about/',views.about, name='register-about'),
    path('myregistration/',views.myregistered, name = 'my-register'),
    path('eventregister/<int:pk>/',views.booking,name='register-create'),
    path('eventregisterdone/',views.bookingdone,name='book-confirm'),
    path('confirmmassattend/',views.confirmmassattend,name='confirmmassattend'),
    path('myregistration/<int:pk>/cancel',RegisterCreateView.as_view(),name='register-cancel')
]

registerformass/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('signin/', user_views.userregister, name='userregister'),
    path('profile/',user_views.profile,name='profile'),
    path('login/',auth_views.LoginView.as_view(template_name='users/login.html'),name='login'),
    path('logout/',auth_views.LogoutView.as_view(template_name='users/logout.html'),name='logout'),
    path('',include('register.urls')),
    path('qr_code/', include('qr_code.urls', namespace="qr_code"))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

register/models.py
from django.db import models
from django.utils import timezone
from django.utils.crypto import get_random_string
from django.contrib.auth.models import User


class Mass(models.Model):
    language_choice = (
        ('JAPANESES','日本語'),
        ('ENGLISH','English'),
        ('SPANISH','Spanish'),
        ('VIETNAMESE','Tiếng Việt')
    )
    mass_date = models.DateField()
    mass_time = models.TimeField()
    mass_title = models.CharField(max_length=100)
    mass_language = models.CharField(max_length=15,choices=language_choice)
    mass_date_ordinary = models.CharField(max_length=100)
    main_celebrant = models.CharField(max_length=40)
    mass_slots = models.SmallIntegerField(default=100)
    mass_slots_registered = models.SmallIntegerField(default=0)
    mass_online_url = models.URLField(blank=True)
    mass_image = models.ImageField(null=True,blank=True,upload_to='mass_images')

class Register(models.Model):
    date_registered = models.DateTimeField(default=timezone.now)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    mass = models.ForeignKey(Mass, on_delete=models.CASCADE)
    seat_number = models.CharField(max_length=100)
    qa_code_text = models.CharField(max_length=200)
    status = models.CharField(max_length=2)

class Event(models.Model):
    language_choice = (
        ('JAPANESES','日本語'),
        ('ENGLISH','English'),
        ('SPANISH','Spanish'),
        ('VIETNAMESE','Tiếng Việt')
    )
    event_date = models.DateTimeField()
    event_time = models.TimeField()
    event_time_length = models.SmallIntegerField(blank=True,default=1)
    event_title = models.CharField(max_length=100)
    event_content = models.TextField(blank=True)
    event_language = models.CharField(max_length=15,choices=language_choice)
    event_date_ordinary = models.CharField(max_length=100)
    event_holder = models.CharField(max_length=40)
    event_slots = models.SmallIntegerField(default=100)
    event_slots_registered = models.SmallIntegerField(default=0)
    event_online_url = models.URLField(blank=True)
    event_image = models.ImageField(null=True,blank=True,upload_to='mass_images')
    event_active = models.BooleanField(default=True)
    event_created_date = models.DateTimeField(default=timezone.now)

class Seat(models.Model):
    seat_choice = (
        ('','Select'),
        ('CHILDREN','For Children'),
        ('OLDER','For Older People'),
        ('NOTWELL','For UnHeathy Peopel'),
        ('YOUNG','For Young People')
    )
    event_choice = (
        ('MASS','Mass'),
        ('EVENT','Event')
    )
    seat_no = models.CharField(max_length=4,null=True,blank=False)
    seat_type = models.CharField(max_length=30,choices=seat_choice, blank=False)
    seat_event = models.CharField(max_length=8,choices=event_choice, blank=False)

    class Meta:
        unique_together = ('seat_no','seat_event')

    def __str__(self):
        return self.seat_no + str(self.seat_event)

class Booking(models.Model):

    status_choice = (
        ('W','Waiting'),
        ('A','Approved'),
        ('D','Denied'),
        ('P','Presented'),
        ('AB','Absented')
    )
    random_code = get_random_string(length=18, allowed_chars='ABCDEFGHabcdefgh12345YUyu')
    booking_date = models.DateTimeField(default=timezone.now)
    booking_user = models.ForeignKey(User, on_delete=models.CASCADE)
    booking_event = models.ForeignKey(Event, on_delete=models.CASCADE)
    booking_seat = models.ForeignKey(Seat, on_delete=models.CASCADE)
    booking_confirm_code = models.CharField(max_length=18,default=random_code)
    booking_code = models.CharField(max_length=300,default='')
    booking_status = models.CharField(max_length=12,choices=status_choice,default='W')
    booking_attend_time = models.DateTimeField(default=timezone.now)
    
    class Meta:
        unique_together = ('booking_seat','booking_event')
    
    def __str__(self):
        return str(self.booking_user)+'-'+str(self.booking_event)+'-'+self.booking_confirm_code
    
    

def event_index(request):
    event_list = Event.object.filter(event_date>=timezone.now, event_active=True)

# Create your models here.

register/forms.py
from django import forms
from .models import Event, Booking

class BookingForm(forms.ModelForm):
    class Meta:
        model = Booking
        fields = ('')

register/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.contrib import messages
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.conf import settings
import sys
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import(
    ListView,
    DeleteView,
    CreateView,
    UpdateView,
    DeleteView
)
from users.forms import ProfileUpdateTemptureForm
from .models import Register, Mass
from .models import Event, Booking, Seat
from users.models import Profile
from django.contrib.auth.models import User


# Create your views here.

def home(request):
    context = {
        'events': Event.objects.all()
    }
    return render(request,'register/home.html', context)

class RegisterCreateView(LoginRequiredMixin, CreateView):
    model = Register
    fields = ['mass','seat_number','qa_code_text','status']

    def form_valid(self,form):
        form.instance.author = self.request.user
        username = form.instance.author.username
        messages.success(self.request, f'Mass Registered for {username}!')
        return super().form_valid(form)

class MassListView(ListView):
    queryset = Event.objects.filter(event_date__gte = timezone.now())   #__lte less than or equal; __gte greater than or equal
    template_name = 'register/home.html' #<app>/<model>_<viewtype>.html
    context_object_name = 'events'
    ordering = ['event_date','event_time']

def about(request):
    return render(request,'register/about.html')

@login_required
def booking(request,pk):
    if request.POST:
        user_temp = request.POST.get('user_temp')
        user_temp_date = request.POST.get('user_temp_check_date')
        print(user_temp_date)
        try:
            user = request.user
            event_id = request.POST.get('event_id')
            print("eventid: "+event_id)
            event = Event.objects.get(pk=event_id)
            print(event.event_slots_registered)
            #Check if user have registered for this event
            if Booking.objects.filter(booking_user=user,booking_event=event):
                messages.warning(request, f'Your account has been registered for this Mass!')
                return render(request,'register/registerfail.html')

            #Save user profile update tempturate self checked
            print(user.username)
            users_profile = user.profile
            users_profile.last_check_tempture = int(user_temp)
            print(users_profile.last_check_tempture)
            users_profile.last_check_tempture_time = user_temp_date
            print(users_profile.last_check_tempture_time)
            users_profile.save()
            print("User profile saved")

            # Booking save
            seat = Seat.objects.get(pk=1)
            print(seat.seat_no)
            booking = Booking(booking_user=user,booking_event=event,booking_seat=seat)
            booking.save()
            print(booking.booking_confirm_code)
            #print(ALLOWED_HOSTS)
            booking.booking_code = settings.HOST_NAME+"confirmmassattend/?prshaid="+str(user.pk)+"&bootouroid="+str(booking.pk)+"&ebenjobid="+str(event_id)+"&adncode="+booking.booking_confirm_code
            print(booking.booking_code)
            booking.save()
            #minus 1 slot
            event.event_slots_registered += 1
            event.save()
            print("Booking saved")
        except:
            print("Internal exception")
            print("Unexpected error: ", sys.exc_info()[0])
            messages.warning(request, f'Something wrong has happened, Please contact the admin')
            return render(request,'register/registerfail.html')
        messages.success(request, f'Your registration for this Mass is successfully!')
        return redirect('register-home')
    else:
        event = Event.objects.get(pk=pk)
        #p_form = ProfileUpdateTemptureForm(instance=request.user.profile)
        #Check whether user is valid to resevate
        context = {
            'event':event
        }
        return render(request,'register/register_form.html',context)

@login_required
def bookingdone(self,request):
    if request.POST:
        user_temp = request.POST.get('user_temp')
        user_temp_date = request.POST.get('user_temp_check_date')
        try:
            #Save user profile update tempturate self checked
            user = self.request.user
            users_profile = Profile.objects.get(user=user)
            #users_profile.last_check_tempture = int(user_temp)
            users_profile.last_check_tempture_time = user_temp_date
            users_profile.save()

            # Booking save
            event_id = request.POST.get('event_id')
            event = Event.objects.get(pk=event_id)
            seat = 0
            booking = Booking(booking_user=user,booking_event=event,booking_seat=seat)
            booking.save()
        except:
            print("abc")
        else:
            return redirect('register/registerfail.html')
        return render(request, 'register/register_confirmation.html')

@login_required
def confirmmassattend(request):
    if request.user.groups.filter(name="Admin").exists():
        user_id = request.GET.get('prshaid',0)
        user = User.objects.get(pk=user_id)
        booking_id = request.GET.get('bootouroid',0)
        event_id = request.GET.get('ebenjobid',0)
        code = request.GET.get('adncode','none')
        booking = Booking.objects.get(pk=booking_id,booking_confirm_code=code)
        if booking.booking_status == "A" or booking.booking_status == "W" :
            booking.booking_status = "P"
            booking.save()
            messages.success(request, f'Welcome '+user.username +' !')
            return redirect('register-home')
        else:
            messages.warning(request, f'This registration is not correct!')
            return redirect('register-home')
    else:
        messages.warning(request, f'You are not allowed to approve it!')
        return redirect('register-home')


@login_required
def myregistered(request):

    user = request.user
    booking = Booking.objects.filter(booking_user=user)
    if booking:
        context = {
            'mybooking':booking
        }
        return render(request,'register/myregistered.html',context)
    else:
        messages.warning(request, f'You did not make any registration!')
        return redirect('register-home')

register/templates/register/about.html
{% extends "registration/base.html" %}
{% block content %}
    <h4>Participants will be accommodated by "first come, first serve" basis.</h4><br>
    <p>Before registering, please make sure that you have read out the following rules and regulations for attending the mass found in the following link: </p>
    <a class="nav-item nav-link" href="https://drive.google.com/file/d/13pZXZQESWZBYUuu6ooxUhVIhk4CLTEf0/view?usp=sharing">Rules and regulations for attending the mass, please read!</a>
    <br>
    <h1>IMPORTANT REMINDERS:</h1>
    <p>1. You may only register one person per registration. If you wish to register another person, please accomplish the online registration twice.</p>
    <p>2. Make sure you input the correct email address. A copy of your responses will be sent to your email address right after you have registered. <br>If you receive this email, it means that your registration was done successfully.</p>
    <p>3. You will receive final instructions and your seat number by email by Saturday night. </p>
    <p>4. Make sure to come at least 30 minutes before the scheduled mass. Late comers will not be accepted. Doors of the church will be closed once the mass has started.</p>
    <p>If you're late, please consider going to other masses:  Spanish mass at 1:30 p.m., Vietnamese mass at 3:00 pm, English Mass at 4:30 p.m., and Japanese mass at 6:00 p.m.</p>
    <p>5. In the event that you shall not be able to attend after registering, please cancel your registration by emailing us at siiyministry@gmail.com. 
        Should you are not able to cancel your registration and you do not show up at church for the mass, we may no longer accept your future registration requests.</p>
{% endblock content %}

register/templates/register/home.html
{% extends "registration/base.html" %}
{% load mathfilters i18n %}
{% block content %}
    {% for event in events %}
      <br>
      <div class="card bg-light">
            <img class="card-img-top" src="/media/{{ event.event_image }}" alt="{{ mass.mass_title }}">
            <div class="card-body  text-center">
              <h5 class="card-text">{% trans "Tổng số ghế: " %}{{ event.event_slots }}</h5>
              <h5 class="article-content">{% trans "Số ghế còn lại: " %}{{ event.event_slots|sub:event.event_slots_registered}}</h5>
              <div class="row">
                  <div class="col-6 text-center">
                      {% if event.event_slots_registered < event.event_slots %}
                      <a href="{% url 'register-create' event.id %}" class="btn btn-info">{% trans "Đăng ký" %}</a>
                      {% endif %}
                  </div>
                  <div class="col-6 text-center">
                      <a href="{% url 'register-create' event.id %}" class="btn btn-info">{% trans "Bài đọc" %}</a>
                  </div>
              </div>
            </div>
      </div>
    {% endfor %}
{% endblock content %}

register/templates/register/myregistered.html
{% extends "registration/base.html" %}
{% load qr_code %}
{% block content %}
    {% for booking in mybooking %}
      <br>
      <div class="card-deck">
          <div class="card bg-light">
            <div class="card-body  text-center">
              <h3 class="card-title">{{ booking.booking_event.event_title }}</h3>
              {% if booking.booking_status == 'A' %}
                <h4>Your reservation code here</h4>
                <img src="{% qr_url_from_text booking.booking_code %}" alt="Hello World!">
              {% endif %}
              <h4 class="card-title">Your seat no: {{ booking.booking_seat.seat_no }}</h4>
              <h5 class="card-text"><a class="nav-item nav-link" href="{{ booking.booking_event.event_online_url }}">Online Streaming </a></h5>
              <h5 class="article-content">Registered on: {{ booking.booking_date }} </h5>
              <h5 class="article-content">Status: {{ booking.get_booking_status_display }} </h5>
              <a href="#" class="btn btn-info">Cancel</a>
            </div>
          </div>
      </div>
    {% endfor %}
{% endblock content %}

register/templates/register/register_confirmation.html
{% extends "registration/base.html" %}
{% block content %}

	<h1>Payment Confirmation</h1>
	<div class="ticket">
			Registration Done!
	</div>

{% endblock %}

register/templates/register/register_form.html
{% extends "registration/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <div class="card bg-light">
            <div class="card-header text-center"><h3>You are registering for this Mass</h3></div>
            <img class="card-img-top" src="/media/{{ event.event_image }}" alt="{{ mass.mass_title }}">
            <div class="card-body  text-center">
              <h4 class="card-text">{{ event.event_title }}</h4>
              <h5 class="success"> Please confirm your heath condition!</h5>
            </div>
        </div><br>
        <form method="POST">
            {% csrf_token %}
            <div class="form-group">
                <label for="user_temp">Your body recent temperature</label>
                <input type="number" class="form-control" name="user_temp" id="user_temp">
            </div>
            <div class="form-group">
                <label for="user_temp_check_date">The day your have checked</label>
                <input type="date" class="form-control" name="user_temp_check_date" id="user_temp_check_date">
            </div>
            <div class="form-group text-center">
                <input type="hidden" name="event_id" id="event_id" value="{{ event.id }}" readonly />
                <button class="btn btn-outline-info" type="submit">Register</button>
                <button class="btn btn-outline-danger" href="{% url 'register-home' %}">Cancel</button>
            </div>
        </form>
    </div>
{% endblock content %}

register/templates/register/registerfail.html
{% extends "registration/base.html" %}
{% block content %}

	<h1>Payment Confirmation</h1>
	<div class="ticket">
			Registration Cannot be done! Please contact to the admin
	</div>

{% endblock %}